#############################################################################
# Makefile for building: StdSockets
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  StdSockets.pro
# Template: subdirs
# Command: /usr/lib/qt5/bin/qmake -o Makefile StdSockets.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = StdSockets1.0.0
DISTDIR = /mnt/d/developpement/devIUT/projets/thegame/.tmp/StdSockets1.0.0
SUBTARGETS    =  \
		sub-ServerAsync \
		sub-ClientAsync


sub-ServerAsync-qmake_all:  FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro
	cd ServerAsync/ && $(MAKE) -f Makefile qmake_all
sub-ServerAsync: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile
sub-ServerAsync-make_first: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile 
sub-ServerAsync-all: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile all
sub-ServerAsync-clean: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile clean
sub-ServerAsync-distclean: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile distclean
sub-ServerAsync-install_subtargets: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile install
sub-ServerAsync-uninstall_subtargets: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile uninstall
sub-ClientAsync-qmake_all:  FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro
	cd ClientAsync/ && $(MAKE) -f Makefile qmake_all
sub-ClientAsync: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile
sub-ClientAsync-make_first: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile 
sub-ClientAsync-all: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile all
sub-ClientAsync-clean: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile clean
sub-ClientAsync-distclean: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile distclean
sub-ClientAsync-install_subtargets: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile install
sub-ClientAsync-uninstall_subtargets: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile uninstall

Makefile: StdSockets.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		StdSockets.pro
	$(QMAKE) -o Makefile StdSockets.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
StdSockets.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile StdSockets.pro

qmake_all: sub-ServerAsync-qmake_all sub-ClientAsync-qmake_all FORCE

make_first: sub-ServerAsync-make_first sub-ClientAsync-make_first  FORCE
all: sub-ServerAsync-all sub-ClientAsync-all  FORCE
clean: sub-ServerAsync-clean sub-ClientAsync-clean  FORCE
distclean: sub-ServerAsync-distclean sub-ClientAsync-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-ServerAsync-install_subtargets sub-ClientAsync-install_subtargets FORCE
uninstall_subtargets: sub-ServerAsync-uninstall_subtargets sub-ClientAsync-uninstall_subtargets FORCE

sub-ServerAsync-check:
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile check
sub-ClientAsync-check:
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile check
check: sub-ServerAsync-check sub-ClientAsync-check

sub-ServerAsync-benchmark:
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -f Makefile benchmark
sub-ClientAsync-benchmark:
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-ServerAsync-benchmark sub-ClientAsync-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-ServerAsync-distdir sub-ClientAsync-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf .qmake.stash /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf StdSockets.pro $(DISTDIR)/

sub-ServerAsync-distdir: FORCE
	@test -d ServerAsync/ || mkdir -p ServerAsync/
	cd ServerAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ServerAsync/ServerAsync.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/ServerAsync

sub-ClientAsync-distdir: FORCE
	@test -d ClientAsync/ || mkdir -p ClientAsync/
	cd ClientAsync/ && ( test -e Makefile || $(QMAKE) -o Makefile /mnt/d/developpement/devIUT/projets/thegame/ClientAsync/ClientAsync.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/ClientAsync

